### ISSUE TITLE
Configure the environment according to environment.yml, but an error is reported.

### ISSUE THREAD

**Issue by StZhang-B** [aeolusguan/NMRF#1]
The error is reported as follows:

(base) D:\Project\NMRF-main>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libstdcxx-ng=11.2.0
  - openh264=2.1.1
  - _openmp_mutex=5.1
  - gmp=6.2.1
  - libunistring=0.9.10
  - libgcc-ng=11.2.0
  - ncurses=6.4
  - ld_impl_linux-64=2.38
  - readline=8.2
  - libtasn1=4.19.0
  - libcufile=1.9.0.20
  - gnutls=3.6.15
  - libidn2=2.3.4
  - libgomp=11.2.0
  - nettle=3.7.3

**Comment by VaderGong** [comment]
Got the same problem as you. How did you solve it? Thx

**Comment by StZhang-B** [comment]
> Got the same problem as you. How did you solve it? Thx

forgotten, it's been too long, sry...

**Comment by aeolusguan** [comment]
Currently, the code is only tested in **Ubuntu**.
