### ISSUE TITLE
Time required for training

### ISSUE THREAD

**Issue by ShunkaiZhou** [aeolusguan/NMRF#10]
Dear author,
Thanks for your great work. I want to train my own dataset, so I would like to know how long this work takes to train on KITTI? (on RTX 3090)
Many thanks in advance and best wishes!!

**Comment by aeolusguan** [comment]
It depends on the training iterations. In my setting (4 RTX 3090, batch size 8, image crop size: 384x768), it takes about 0.41 per iteration.

**Comment by ShunkaiZhou** [comment]
OK. Thank you for your rapid reply!
Best wishes!
