### ISSUE TITLE
Is the network 'fixed' by dataset?

### ISSUE THREAD

**Issue by zhongqiu1245** [aeolusguan/NMRF#2]
Hello, thank you for your amazing job!
I have a question about your work.
Is the network 'fixed' by dataset?
I mean if I use kitti_pth to my own dataset(the params of cameras are different with kitti cameras totally), can I get the right depth?
Thank you!

**Comment by aeolusguan** [comment]
This network only predicts the _disparity_ of between left & right views. Afterwards, you can compute the depth using the well-known [formula](https://answers.opencv.org/question/199915/how-to-get-depth-from-disparity-map/) based on the disparity and your camera parameters.

**Comment by zhongqiu1245** [comment]
@aeolusguan thank you for your reply!
I mean the baseline of my setero camera is totally different with kitti, can I get the correct disparity by kitti_pth?
And according your answear, why do we distinguish between kitti_pth and other_pth, can't we just use one pth to detect all?

**Comment by aeolusguan** [comment]
- The difference between kitty_pth and other_pth lies the different training set we use. It would be a promising way to mix different datasets and get a single model to detect all.
- The disparity prediction is not highly correlated with the baseline of stereo camera. If your custom data is also from autonomous driving scenarios like KITTI, and not too large (I recommend the stereo image <720p), I think you would get good disparity regardless of the difference in baseline.

**Comment by zhongqiu1245** [comment]
@aeolusguan Thank you!
