### ISSUE TITLE
Poor Results Using Pretrained Model

### ISSUE THREAD

**Issue by wattanakorn495** [aeolusguan/NMRF#3]
I am using the pretrained weights provided in Google Drive, but the model is giving me poor results compared to the results submitted on the KITTI benchmark.

example result
![000000_10](https://github.com/user-attachments/assets/7299e4d7-a77d-403a-9794-985e51213c2d)
![000001_10](https://github.com/user-attachments/assets/261b16c3-dc90-42d7-91e8-41d42c004b4a)

**Comment by aeolusguan** [comment]
which model did you use? The model using SwinT as backbone?

**Comment by wattanakorn495** [comment]
Oh, I used the wrong image paths. The correct ones are:

colored_0/000000_10.png
colored_1/000000_10.png

I had mistakenly used:
colored_0/000000_10.png
colored_0/000000_11.png
I’ll fix this and check the results again.
