### ISSUE TITLE
About Swint as a backbone

### ISSUE THREAD

**Issue by zhcm** [aeolusguan/NMRF#4]
Thank you for your hard work. Will you release the config file and pretrained weights for Swint as a backbone for SceneFlow training?

**Comment by aeolusguan** [comment]
Hi, the config file has been uploaded and commands to pretrain on SceneFlow are added to the [doc](https://github.com/aeolusguan/NMRF/blob/main/docs/swint.md).

**Comment by aeolusguan** [comment]
The model (SwinT backbone) pre-trained on SceneFlow is now available at [google drive](https://drive.google.com/file/d/1eR2ARJYqMyGmInIIQ7XV3RvAwYlvDrBV/view?usp=drive_link).
