### ISSUE TITLE
Possibility Adapting NMRF into a Self-Supervised Network.

### ISSUE THREAD

**Issue by Magicboomliu** [aeolusguan/NMRF#5]
Hi! Outstanding works.

I am writing this issue just to discuss whether we can use the `NMRF` in a self-supervised manner without using the ground truth disparity.    

The main question is how to apply the `Disparity Proposal Loss` in a self-supervised manner since it requires the GT disparity for matching. Thanks a lot if you are interested.

**Comment by aeolusguan** [comment]
Thanks for your interest in our work. If `Disparity Proposal Loss` is your main concern, the `Disparity Proposal Network` could be replaced with another NMRF inference stage, which only slight performance drop in the supervised setting. Good Luck! :muscle:
