### ISSUE TITLE
gray images inference 

### ISSUE THREAD

**Issue by pullitdown** [aeolusguan/NMRF#6]
Hi! I'm really fascinated by the zero-shot ability discussed in this paper. I'm trying to use my gray stereo camera to predict real-world disparity. However, when I fine-tuned the pre-trained model with grayscale images from the KITTI dataset for about 300 epochs, the results seem to get worse. Should I use the entire dataset for fine-tuning, or is there a better approach you could suggest?
For image processing, I read the image as a grayscale image and stack three identical grayscale channels as the model input.

**Comment by aeolusguan** [comment]
Which model did you use? The original or that with SwinT backbone. I have found that the model with SwinT backbone does not generalize well to gray image.

**Comment by pullitdown** [comment]
i use original one. the results are as follows
![Screenshot from 2024-10-18 10-56-40](https://github.com/user-attachments/assets/3ed72524-724b-41b3-9fe5-0aec9e156c68)
the results seem that the pretrained one better than fine-tuned model.

**Comment by pullitdown** [comment]
Thank you very much, I will test with a new dataset, and then post the results back to the reply.

**Comment by pullitdown** [comment]
![Screenshot from 2024-11-07 10-30-58](https://github.com/user-attachments/assets/fc6b5122-d16f-4445-8c60-dc9040ce2a85)
fine-tuning with IRS dataset contained reflection scene  and the infer result get better.

**Comment by ShunkaiZhou** [comment]
@pullitdown Hi, thank you for your excellent questions. 
I am also trying to test the indoor scene, could you please share your weights after fine-tune for the indoor scene?
Thank you very much and best wishes!
